### ISSUE TITLE
Does this library support react native? 

### ISSUE THREAD

**Issue by serhii-yalla** [at-point-of-sale/ReceiptPrinterEncoder#36]
If so, what version is it support? For my case, I am on 0.75.3 version of react native.

**Comment by serhii-yalla** [comment]
BTW. Tried latest 3.0.1 version. Built successful, but not working. Code after calling class construct display that.
```
 (NOBRIDGE) ERROR  [ReferenceError: Property 'structuredClone' doesn't exist] 
 ```

**Comment by NielsLeenheer** [comment]
Apparently Hermes does not support `structuredClone()`... which is a bit surprising.
https://github.com/facebook/hermes/issues/684

I'll see if I can include a polyfill in the next update.

**Comment by serhii-yalla** [comment]
@NielsLeenheer May I ask you to add some variants to print images on web and mobile side? Cause I can't find a way to pass image data to image method of escpos builder 🫶

**Comment by NielsLeenheer** [comment]
In the examples directory there are a lot of libraries that can be used with ReceiptPrinterEncoder, and some are plain JavaScript, so I am sure some of them support React Native as well. But I am not familiar with how React Native works, so I can't give you examples of how to use it.

https://github.com/NielsLeenheer/ReceiptPrinterEncoder/tree/main/examples/images

**Comment by karaushu** [comment]
Got something similar: `Cannot find 'ImageData' in browser.js (3:18)`.
Expo 51, React Native, 0.74.5, hermes engine. It's try to import an canvas with will not work in RN.

**Comment by NielsLeenheer** [comment]
That main be an issue with the bundler your project is using. ImageData is import from the `@canvas/image-data` package. That package has two code paths: one for the browser and one for Node. Apparently the bundler picks the path for the browser. And then it expects the browser native `ImageData` to be there. Which it isn't. 

Not sure if that is helpful or not. Maybe the `@canvas/image-data` package itself is not React Native compatible. If that is the issue then perhaps we can work around it in a future version. 

Ideally, for better React Native support I would need a sample project somewhere on Github which I could clone and play around with, without having to learn React Native from the ground up.

**Comment by karaushu** [comment]
You can use Expo Snack, it's an easy way to test lib on real devices. Here is [example](https://snack.expo.dev/@expo_karaushu/receiptprinterencoder)

**Comment by ibrahimkundlik** [comment]
@serhii-yalla @karaushu Were you guys able to figure out if **ReceiptPrinterEncoder** can work correctly with react-native or not ?

I am also getting the same error around `structuredClone` as mentioned by @serhii-yalla in above comment.

**Comment by antoniozh** [comment]
I'm using 2.1.1 as of now because this does not run on RN for me, hopefully ImageData can be replaced/substituted for React Native developers

**Comment by vasu2001** [comment]
I have created a PR on @canvas/image-path in order to fix the resolution problem on react-native
https://github.com/node-gfx/image-data/pull/4

**Comment by LinusU** [comment]
I've released ImageData [🚢 1.1.0 / 2025-10-14](https://github.com/node-gfx/image-data/releases/tag/v1.1.0) which points to the correct file for React Native 🚀

**Comment by antoniozh** [comment]
It works for me with one workaround: I had to redeclare structuredClone, seems like the constructor required it. Thank you!

**Comment by NielsLeenheer** [comment]
Is structuredClone still an issue on React Native? I've tried to use in an a Expo 54 project and it seemed to work?

**Comment by NielsLeenheer** [comment]
Closing this one with a summary, since it collects everything that came up.

There were two separate problems in this thread. The `ImageData` one was in `@canvas/image-data`, which resolved to its browser file under Metro. That is fixed upstream in 1.1.0, thanks to @vasu2001 for the PR and @LinusU for the quick release, and version 4.0.0 of the encoder picks it up.

The `structuredClone` one is Hermes not providing it. Newer Hermes builds seem to have it, an Expo 54 project worked for me without anything extra, but on older React Native versions you still need a polyfill. The usage docs now have a section for this: https://github.com/at-point-of-sale/ReceiptPrinterEncoder/blob/main/documentation/usage.md#using-with-react-native-and-expo. It comes down to installing `@ungap/structured-clone` and assigning it to `globalThis.structuredClone` before the encoder is imported.

For images: the encoder does not decode anything itself. Give `image()` an object with `width`, `height` and RGBA pixel `data`, from whichever decoder works in your app, and it takes it from there.

If something else breaks on React Native with 4.0.0, please open a new issue with the version and the error.
